### ISSUE TITLE
所有项目同步到码云

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/mgithub#3]
考虑到安全和配合国产化战略，码云也需要同步github上的所有项目

**Comment by chendelin1982** [comment]
方案探索：
1. Gitee 上导入 Github 上的项目
2. Github Action 主动更新 Gitee 上的同名项目，[参考方案](https://qq52o.me/2768.html)

**Comment by qiaofeng1227** [comment]
1,需要实时同步
2,requirements.yml的源码地址需要更换成码云的src地址

**Comment by qiaofeng1227** [comment]
Done

**Comment by qiaofeng1227** [comment]
1. 同步的触发条件是 github的main分支发生改变，但是每次同步都需要全部main分支和dev分支的内容
2. docker项目目前只有这两个
![image](https://user-images.githubusercontent.com/43192516/115807646-9cff9580-a41b-11eb-8890-d2b307abb8cf.png)
3. ansible项目只有这个两个
![image](https://user-images.githubusercontent.com/43192516/115807731-c02a4500-a41b-11eb-82f0-ab4c73c44694.png)
4.role开头的项目只有一个
![image](https://user-images.githubusercontent.com/43192516/115807821-e6e87b80-a41b-11eb-9129-75f4be510d32.png)

注意：通过mgithub删除，copy的时候，docker-template除外，它是所有文件的基础来源，是最全的。对这个工程的workflows不要操作

**Comment by qiaofeng1227** [comment]
文档追加：
添加位置 Q&A
1,如果使用的SCL源安装的python3.8或者更高的版本来执行mgithub，其使用流程是什么样的？
cd /opt/rh ...

2,mgithub modify 支持以下执行多条命令或者执行脚本？如何准备sh文件，放置位置，请描述

**Comment by qiaofeng1227** [comment]
Done
