### ISSUE TITLE
根据设置url组织获取 repolist

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/mgithub#5]
## Steps to reproduce the bug

[root@VM-81-187-centos mgithub-dev]# mgithub copy template/test .
[[copy]] function is running
src_path: template/test
des_path: .
url: https://github.com/cloud-install

## Print Screen of the bug
![image](https://user-images.githubusercontent.com/43192516/106835342-28e20b00-66d2-11eb-90d4-55c63e5ca8e7.png)

实际该组织下3个repo，清单里面变成了6个

## Context information (for bug reports)

**Output error of `shell`**
```
未完成清单内容如下：
testproject
Apache License 2.0
ansible-lcmp
Other
ansible-awx
Other
```

**Comment by Alanspants** [comment]
在config中添加repogrep属性
默认为空，可能会出现类似的project name识别错误问题，建议使用--skip-broken跳过
repogrep = ansible,test
仅对当前组织或个人的以ansible或test开头的仓库进行操作

**Comment by qiaofeng1227** [comment]
Done
