### ISSUE TITLE
日志的文件日期 只有时间，最好把年月日加上 

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/mgithub#6]
![image](https://user-images.githubusercontent.com/43192516/106851653-9baeae80-66f1-11eb-85a8-59fe0bba6d1f.png)

date_format：YYYY-MM-DD HH:mm:ss

**Comment by Alanspants** [comment]
nowtime = time.strftime("%Y%m%d %H:%M:%S")
![Uploading 截屏2021-02-04 20.24.14.png…]()

**Comment by qiaofeng1227** [comment]
Done
