### ISSUE TITLE
需求变更：取消业务方法拉取github项目的功能部分

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/mgithub#7]
变更原因：考虑到用户的工作清单千变万化，无法通过拉取所有项目或正则表达式筛选后的项目清单来工作，故将清单准备的工作前置，所以所有业务方法不再拉取项目，而是对直接针对repository.txt的项目开始工作；

条件判断：
如果 repository.txt 为空，退出
如果 repopitory.txt 不为空，则询问用户是否工作，等待确认后才开始工作；取消退出

**Comment by Alanspants** [comment]
重构策略：
mgithub/data/XXXXX_repositories.txt: 项目列表；由mgithub repocache命令生成，用户可自行更改。存放用户想要对其进         行操作的projects。
mgithub/data/cache.txt：缓存列表；在任务开始时，与项目列表保持一致，完成一个project则删除cache.txt中对应的line。未完成或失败的任务则保留在cache.txt中。任务开始时通过cache.txt文件判断上次任务是否完成，如未完成，由用户判断是否需要断点续执行。

**Comment by qiaofeng1227** [comment]
Done
